name: sheril

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: 'sheril'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3311:3306'
    expose:
      - '3311'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./divers/base_sheril.sql:/docker-entrypoint-initdb.d/base_sheril.sql

  console:
    build: .
    ports:
      - "666:80"
    volumes:
      - ./php:/var/www/html
    restart: unless-stopped
    depends_on:
      - db

  ## MOTEUR DE JEU (JAVA)
  engine:
    image: eclipse-temurin:21-jdk
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["tail", "-f", "/dev/null"] # Maintient le conteneur actif en tâche de fond
    depends_on:
      - db